/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as ChildSafetyRouteImport } from './routes/child-safety'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SmartHomeIndexRouteImport } from './routes/smart-home/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as CareersIndexRouteImport } from './routes/careers/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SmartHomeGoogleHomeRouteImport } from './routes/smart-home/google-home'
import { Route as SmartHomeControl4RouteImport } from './routes/smart-home/control4'
import { Route as SmartHomeAppleHomekitRouteImport } from './routes/smart-home/apple-homekit'
import { Route as SmartHomeAlexaRouteImport } from './routes/smart-home/alexa'
import { Route as LocationsCityRouteImport } from './routes/locations/$city'
import { Route as BookingConfirmedRouteImport } from './routes/booking/confirmed'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LocationsCityProductRouteImport } from './routes/locations/$city.$product'
import { Route as CareersCityPositionRouteImport } from './routes/careers/$city.$position'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildSafetyRoute = ChildSafetyRouteImport.update({
  id: '/child-safety',
  path: '/child-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeIndexRoute = SmartHomeIndexRouteImport.update({
  id: '/smart-home/',
  path: '/smart-home/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeGoogleHomeRoute = SmartHomeGoogleHomeRouteImport.update({
  id: '/smart-home/google-home',
  path: '/smart-home/google-home',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeControl4Route = SmartHomeControl4RouteImport.update({
  id: '/smart-home/control4',
  path: '/smart-home/control4',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeAppleHomekitRoute = SmartHomeAppleHomekitRouteImport.update({
  id: '/smart-home/apple-homekit',
  path: '/smart-home/apple-homekit',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHomeAlexaRoute = SmartHomeAlexaRouteImport.update({
  id: '/smart-home/alexa',
  path: '/smart-home/alexa',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => BookingRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityProductRoute = LocationsCityProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => LocationsCityRoute,
} as any)
const CareersCityPositionRoute = CareersCityPositionRouteImport.update({
  id: '/careers/$city/$position',
  path: '/careers/$city/$position',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/child-safety': typeof ChildSafetyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inspiration': typeof InspirationRoute
  '/legal': typeof LegalRoute
  '/reviews': typeof ReviewsRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/booking/confirmed': typeof BookingConfirmedRoute
  '/locations/$city': typeof LocationsCityRouteWithChildren
  '/smart-home/alexa': typeof SmartHomeAlexaRoute
  '/smart-home/apple-homekit': typeof SmartHomeAppleHomekitRoute
  '/smart-home/control4': typeof SmartHomeControl4Route
  '/smart-home/google-home': typeof SmartHomeGoogleHomeRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/smart-home/': typeof SmartHomeIndexRoute
  '/careers/$city/$position': typeof CareersCityPositionRoute
  '/locations/$city/$product': typeof LocationsCityProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/child-safety': typeof ChildSafetyRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inspiration': typeof InspirationRoute
  '/legal': typeof LegalRoute
  '/reviews': typeof ReviewsRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/booking/confirmed': typeof BookingConfirmedRoute
  '/locations/$city': typeof LocationsCityRouteWithChildren
  '/smart-home/alexa': typeof SmartHomeAlexaRoute
  '/smart-home/apple-homekit': typeof SmartHomeAppleHomekitRoute
  '/smart-home/control4': typeof SmartHomeControl4Route
  '/smart-home/google-home': typeof SmartHomeGoogleHomeRoute
  '/blog/': typeof BlogIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/smart-home/': typeof SmartHomeIndexRoute
  '/careers/$city/$position': typeof CareersCityPositionRoute
  '/locations/$city/$product': typeof LocationsCityProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/booking' | '/catalog' | '/child-safety' | '/commercial' | '/contact' | '/faq' | '/inspiration' | '/legal' | '/reviews' | '/warranty' | '/blog/$slug' | '/booking/confirmed' | '/locations/$city' | '/smart-home/alexa' | '/smart-home/apple-homekit' | '/smart-home/control4' | '/smart-home/google-home' | '/blog/' | '/careers/' | '/locations/' | '/smart-home/' | '/careers/$city/$position' | '/locations/$city/$product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/booking' | '/catalog' | '/child-safety' | '/commercial' | '/contact' | '/faq' | '/inspiration' | '/legal' | '/reviews' | '/warranty' | '/blog/$slug' | '/booking/confirmed' | '/locations/$city' | '/smart-home/alexa' | '/smart-home/apple-homekit' | '/smart-home/control4' | '/smart-home/google-home' | '/blog' | '/careers' | '/locations' | '/smart-home' | '/careers/$city/$position' | '/locations/$city/$product'
  id: '__root__' | '/' | '/about' | '/booking' | '/catalog' | '/child-safety' | '/commercial' | '/contact' | '/faq' | '/inspiration' | '/legal' | '/reviews' | '/warranty' | '/blog/$slug' | '/booking/confirmed' | '/locations/$city' | '/smart-home/alexa' | '/smart-home/apple-homekit' | '/smart-home/control4' | '/smart-home/google-home' | '/blog/' | '/careers/' | '/locations/' | '/smart-home/' | '/careers/$city/$position' | '/locations/$city/$product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  ChildSafetyRoute: typeof ChildSafetyRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InspirationRoute: typeof InspirationRoute
  LegalRoute: typeof LegalRoute
  ReviewsRoute: typeof ReviewsRoute
  WarrantyRoute: typeof WarrantyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LocationsCityRoute: typeof LocationsCityRouteWithChildren
  SmartHomeAlexaRoute: typeof SmartHomeAlexaRoute
  SmartHomeAppleHomekitRoute: typeof SmartHomeAppleHomekitRoute
  SmartHomeControl4Route: typeof SmartHomeControl4Route
  SmartHomeGoogleHomeRoute: typeof SmartHomeGoogleHomeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  SmartHomeIndexRoute: typeof SmartHomeIndexRoute
  CareersCityPositionRoute: typeof CareersCityPositionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': { id: '/warranty'; path: '/warranty'; fullPath: '/warranty'; preLoaderRoute: typeof WarrantyRouteImport; parentRoute: typeof rootRouteImport }
    '/reviews': { id: '/reviews'; path: '/reviews'; fullPath: '/reviews'; preLoaderRoute: typeof ReviewsRouteImport; parentRoute: typeof rootRouteImport }
    '/legal': { id: '/legal'; path: '/legal'; fullPath: '/legal'; preLoaderRoute: typeof LegalRouteImport; parentRoute: typeof rootRouteImport }
    '/inspiration': { id: '/inspiration'; path: '/inspiration'; fullPath: '/inspiration'; preLoaderRoute: typeof InspirationRouteImport; parentRoute: typeof rootRouteImport }
    '/faq': { id: '/faq'; path: '/faq'; fullPath: '/faq'; preLoaderRoute: typeof FaqRouteImport; parentRoute: typeof rootRouteImport }
    '/contact': { id: '/contact'; path: '/contact'; fullPath: '/contact'; preLoaderRoute: typeof ContactRouteImport; parentRoute: typeof rootRouteImport }
    '/commercial': { id: '/commercial'; path: '/commercial'; fullPath: '/commercial'; preLoaderRoute: typeof CommercialRouteImport; parentRoute: typeof rootRouteImport }
    '/child-safety': { id: '/child-safety'; path: '/child-safety'; fullPath: '/child-safety'; preLoaderRoute: typeof ChildSafetyRouteImport; parentRoute: typeof rootRouteImport }
    '/catalog': { id: '/catalog'; path: '/catalog'; fullPath: '/catalog'; preLoaderRoute: typeof CatalogRouteImport; parentRoute: typeof rootRouteImport }
    '/booking': { id: '/booking'; path: '/booking'; fullPath: '/booking'; preLoaderRoute: typeof BookingRouteImport; parentRoute: typeof rootRouteImport }
    '/about': { id: '/about'; path: '/about'; fullPath: '/about'; preLoaderRoute: typeof AboutRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/smart-home/': { id: '/smart-home/'; path: '/smart-home'; fullPath: '/smart-home/'; preLoaderRoute: typeof SmartHomeIndexRouteImport; parentRoute: typeof rootRouteImport }
    '/locations/': { id: '/locations/'; path: '/locations'; fullPath: '/locations/'; preLoaderRoute: typeof LocationsIndexRouteImport; parentRoute: typeof rootRouteImport }
    '/careers/': { id: '/careers/'; path: '/careers'; fullPath: '/careers/'; preLoaderRoute: typeof CareersIndexRouteImport; parentRoute: typeof rootRouteImport }
    '/blog/': { id: '/blog/'; path: '/blog'; fullPath: '/blog/'; preLoaderRoute: typeof BlogIndexRouteImport; parentRoute: typeof rootRouteImport }
    '/smart-home/google-home': { id: '/smart-home/google-home'; path: '/smart-home/google-home'; fullPath: '/smart-home/google-home'; preLoaderRoute: typeof SmartHomeGoogleHomeRouteImport; parentRoute: typeof rootRouteImport }
    '/smart-home/control4': { id: '/smart-home/control4'; path: '/smart-home/control4'; fullPath: '/smart-home/control4'; preLoaderRoute: typeof SmartHomeControl4RouteImport; parentRoute: typeof rootRouteImport }
    '/smart-home/apple-homekit': { id: '/smart-home/apple-homekit'; path: '/smart-home/apple-homekit'; fullPath: '/smart-home/apple-homekit'; preLoaderRoute: typeof SmartHomeAppleHomekitRouteImport; parentRoute: typeof rootRouteImport }
    '/smart-home/alexa': { id: '/smart-home/alexa'; path: '/smart-home/alexa'; fullPath: '/smart-home/alexa'; preLoaderRoute: typeof SmartHomeAlexaRouteImport; parentRoute: typeof rootRouteImport }
    '/locations/$city': { id: '/locations/$city'; path: '/locations/$city'; fullPath: '/locations/$city'; preLoaderRoute: typeof LocationsCityRouteImport; parentRoute: typeof rootRouteImport }
    '/booking/confirmed': { id: '/booking/confirmed'; path: '/confirmed'; fullPath: '/booking/confirmed'; preLoaderRoute: typeof BookingConfirmedRouteImport; parentRoute: typeof BookingRoute }
    '/blog/$slug': { id: '/blog/$slug'; path: '/blog/$slug'; fullPath: '/blog/$slug'; preLoaderRoute: typeof BlogSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/locations/$city/$product': { id: '/locations/$city/$product'; path: '/$product'; fullPath: '/locations/$city/$product'; preLoaderRoute: typeof LocationsCityProductRouteImport; parentRoute: typeof LocationsCityRoute }
    '/careers/$city/$position': { id: '/careers/$city/$position'; path: '/careers/$city/$position'; fullPath: '/careers/$city/$position'; preLoaderRoute: typeof CareersCityPositionRouteImport; parentRoute: typeof rootRouteImport }
  }
}

interface BookingRouteChildren { BookingConfirmedRoute: typeof BookingConfirmedRoute }
const BookingRouteChildren: BookingRouteChildren = { BookingConfirmedRoute: BookingConfirmedRoute }
const BookingRouteWithChildren = BookingRoute._addFileChildren(BookingRouteChildren)

interface LocationsCityRouteChildren { LocationsCityProductRoute: typeof LocationsCityProductRoute }
const LocationsCityRouteChildren: LocationsCityRouteChildren = { LocationsCityProductRoute: LocationsCityProductRoute }
const LocationsCityRouteWithChildren = LocationsCityRoute._addFileChildren(LocationsCityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, AboutRoute, BookingRoute: BookingRouteWithChildren, CatalogRoute, ChildSafetyRoute,
  CommercialRoute, ContactRoute, FaqRoute, InspirationRoute, LegalRoute, ReviewsRoute, WarrantyRoute,
  BlogSlugRoute, LocationsCityRoute: LocationsCityRouteWithChildren, SmartHomeAlexaRoute,
  SmartHomeAppleHomekitRoute, SmartHomeControl4Route, SmartHomeGoogleHomeRoute,
  BlogIndexRoute, CareersIndexRoute, LocationsIndexRoute, SmartHomeIndexRoute, CareersCityPositionRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
